backend:
  name: git-gateway
  branch: main

media_folder: "static/img/uploads"   # where uploaded files go in repo
public_folder: "/img/uploads"        # how they’re served on site

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"           # so each post is a page bundle
    extension: "md"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Body", name: "body", widget: "markdown"}